### PR TITLE
Moved to Rocket 0.5.0-rc.1

### PR DESCRIPTION
**Pull request by StappsWorld**
Converted the Read trait to AsyncRead and moved an async model. (This solution is a bit janky since the poll_read function is non-async, so I had to use futures::executor::block_on to allow the Tokio runtime to block) Please read through my contributions and verify this still does what the original crate intended. I believe it does, but I'm not the original maintainer. Thanks!

### CODE REVIEW

**Comment by ClementNerma** [comment]
LGTM, @rydz could you take a look at it if you have time :) ?
It would be very nice indeed to get full async support with Rocket 0.5.

**EDIT:** I tried the PR on a local project as it works perfectly 👌

**Comment by mutantcornholio** [comment]
@rydz any chance on merging this? I've currently used the fork, but it would be nice to have an update in original repo

**Comment by rydz** [comment]
Thanks for the PR, sorry for the long delay.
I haven't been keeping up with rocket-rs and rust changes lately.

**Comment by mutantcornholio** [comment]
> Thanks for the PR, sorry for the long delay. I haven't been keeping up with rocket-rs and rust changes lately.

thank you ❤️

**Pull request merged**
